---
title: "DataCamp Course"
author: "Alexandra Stephens"
date: "9/7/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## "Introduction to the Tidyverse" Code Samples

Here is a sample of an exercise I completed in the DataCamp course "Introduction to the Tidyverse"

```{r cars}
library(gapminder)
library(dplyr)
library(ggplot2)

# Summarize medianGdpPercap within each continent within each year: by_year_continent
by_year_continent <- gapminder %>%
  group_by(continent,year) %>%
  summarize(medianGdpPercap = median(gdpPercap))


# Plot the change in medianGdpPercap in each continent over time
ggplot(by_year_continent, aes(x = year,y = medianGdpPercap, color = continent))+
  geom_point() +
  expand_limits(y=0)
```

## Second example: Multiple plots


```{r Multigraph, echo=TRUE}
library(gapminder)
library(dplyr)
library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Scatter plot comparing pop and lifeExp, faceted by continent
ggplot(gapminder_1952, aes(x=pop,y=lifeExp))+ 
  geom_point() +
  scale_x_log10() + 
  facet_wrap(~continent)
```
